// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: katartismos/provisioner.proto

package katartismos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvisionerService_Provision_FullMethodName = "/katartismos.ProvisionerService/Provision"
)

// ProvisionerServiceClient is the client API for ProvisionerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProvisionerService applies manifests to a cluster and prunes resources
// no longer in the rendered output.
type ProvisionerServiceClient interface {
	Provision(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProvisionRequest, ProvisionResponse], error)
}

type provisionerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionerServiceClient(cc grpc.ClientConnInterface) ProvisionerServiceClient {
	return &provisionerServiceClient{cc}
}

func (c *provisionerServiceClient) Provision(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProvisionRequest, ProvisionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProvisionerService_ServiceDesc.Streams[0], ProvisionerService_Provision_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProvisionRequest, ProvisionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisionerService_ProvisionClient = grpc.ClientStreamingClient[ProvisionRequest, ProvisionResponse]

// ProvisionerServiceServer is the server API for ProvisionerService service.
// All implementations must embed UnimplementedProvisionerServiceServer
// for forward compatibility.
//
// ProvisionerService applies manifests to a cluster and prunes resources
// no longer in the rendered output.
type ProvisionerServiceServer interface {
	Provision(grpc.ClientStreamingServer[ProvisionRequest, ProvisionResponse]) error
	mustEmbedUnimplementedProvisionerServiceServer()
}

// UnimplementedProvisionerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionerServiceServer struct{}

func (UnimplementedProvisionerServiceServer) Provision(grpc.ClientStreamingServer[ProvisionRequest, ProvisionResponse]) error {
	return status.Error(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedProvisionerServiceServer) mustEmbedUnimplementedProvisionerServiceServer() {}
func (UnimplementedProvisionerServiceServer) testEmbeddedByValue()                            {}

// UnsafeProvisionerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionerServiceServer will
// result in compilation errors.
type UnsafeProvisionerServiceServer interface {
	mustEmbedUnimplementedProvisionerServiceServer()
}

func RegisterProvisionerServiceServer(s grpc.ServiceRegistrar, srv ProvisionerServiceServer) {
	// If the following call panics, it indicates UnimplementedProvisionerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisionerService_ServiceDesc, srv)
}

func _ProvisionerService_Provision_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProvisionerServiceServer).Provision(&grpc.GenericServerStream[ProvisionRequest, ProvisionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisionerService_ProvisionServer = grpc.ClientStreamingServer[ProvisionRequest, ProvisionResponse]

// ProvisionerService_ServiceDesc is the grpc.ServiceDesc for ProvisionerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisionerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "katartismos.ProvisionerService",
	HandlerType: (*ProvisionerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Provision",
			Handler:       _ProvisionerService_Provision_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "katartismos/provisioner.proto",
}
