// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: katartismos/provisioner.proto

package katartismos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Streamed Kubernetes manifest.
type ProvisionStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionStreamRequest) Reset() {
	*x = ProvisionStreamRequest{}
	mi := &file_katartismos_provisioner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionStreamRequest) ProtoMessage() {}

func (x *ProvisionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionStreamRequest.ProtoReflect.Descriptor instead.
func (*ProvisionStreamRequest) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionStreamRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Provisioned Kubernetes manifest.
type ProvisionStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionStreamResponse) Reset() {
	*x = ProvisionStreamResponse{}
	mi := &file_katartismos_provisioner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionStreamResponse) ProtoMessage() {}

func (x *ProvisionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionStreamResponse.ProtoReflect.Descriptor instead.
func (*ProvisionStreamResponse) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionStreamResponse) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Streamed Kubernetes manifest.
type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      []byte                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_katartismos_provisioner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// Provisioned Kubernetes manifest.
type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_katartismos_provisioner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{3}
}

var File_katartismos_provisioner_proto protoreflect.FileDescriptor

const file_katartismos_provisioner_proto_rawDesc = "" +
	"\n" +
	"\x1dkatartismos/provisioner.proto\x12\vkatartismos\"4\n" +
	"\x16ProvisionStreamRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"5\n" +
	"\x17ProvisionStreamResponse\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\".\n" +
	"\x10ProvisionRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\fR\bmanifest\"\x13\n" +
	"\x11ProvisionResponse2\xc4\x01\n" +
	"\x12ProvisionerService\x12`\n" +
	"\x0fProvisionStream\x12#.katartismos.ProvisionStreamRequest\x1a$.katartismos.ProvisionStreamResponse(\x010\x01\x12L\n" +
	"\tProvision\x12\x1d.katartismos.ProvisionRequest\x1a\x1e.katartismos.ProvisionResponse(\x01B#Z!github.com/katastroma/katartismosb\x06proto3"

var (
	file_katartismos_provisioner_proto_rawDescOnce sync.Once
	file_katartismos_provisioner_proto_rawDescData []byte
)

func file_katartismos_provisioner_proto_rawDescGZIP() []byte {
	file_katartismos_provisioner_proto_rawDescOnce.Do(func() {
		file_katartismos_provisioner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_katartismos_provisioner_proto_rawDesc), len(file_katartismos_provisioner_proto_rawDesc)))
	})
	return file_katartismos_provisioner_proto_rawDescData
}

var file_katartismos_provisioner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_katartismos_provisioner_proto_goTypes = []any{
	(*ProvisionStreamRequest)(nil),  // 0: katartismos.ProvisionStreamRequest
	(*ProvisionStreamResponse)(nil), // 1: katartismos.ProvisionStreamResponse
	(*ProvisionRequest)(nil),        // 2: katartismos.ProvisionRequest
	(*ProvisionResponse)(nil),       // 3: katartismos.ProvisionResponse
}
var file_katartismos_provisioner_proto_depIdxs = []int32{
	0, // 0: katartismos.ProvisionerService.ProvisionStream:input_type -> katartismos.ProvisionStreamRequest
	2, // 1: katartismos.ProvisionerService.Provision:input_type -> katartismos.ProvisionRequest
	1, // 2: katartismos.ProvisionerService.ProvisionStream:output_type -> katartismos.ProvisionStreamResponse
	3, // 3: katartismos.ProvisionerService.Provision:output_type -> katartismos.ProvisionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_katartismos_provisioner_proto_init() }
func file_katartismos_provisioner_proto_init() {
	if File_katartismos_provisioner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_katartismos_provisioner_proto_rawDesc), len(file_katartismos_provisioner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_katartismos_provisioner_proto_goTypes,
		DependencyIndexes: file_katartismos_provisioner_proto_depIdxs,
		MessageInfos:      file_katartismos_provisioner_proto_msgTypes,
	}.Build()
	File_katartismos_provisioner_proto = out.File
	file_katartismos_provisioner_proto_goTypes = nil
	file_katartismos_provisioner_proto_depIdxs = nil
}
