// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: katartismos/provisioner.proto

package katartismos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Streamed manifests to be applied.
//
// labels and service_account are read from the first message only — they do
// not change across the stream. Consider using a oneof to separate metadata
// from data chunks if this becomes a concern.
type ProvisionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ServiceAccount string                 `protobuf:"bytes,3,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_katartismos_provisioner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProvisionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ProvisionRequest) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

// Provision result.
type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_katartismos_provisioner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_katartismos_provisioner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_katartismos_provisioner_proto_rawDescGZIP(), []int{1}
}

var File_katartismos_provisioner_proto protoreflect.FileDescriptor

const file_katartismos_provisioner_proto_rawDesc = "" +
	"\n" +
	"\x1dkatartismos/provisioner.proto\x12\vkatartismos\"\xcd\x01\n" +
	"\x10ProvisionRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12A\n" +
	"\x06labels\x18\x02 \x03(\v2).katartismos.ProvisionRequest.LabelsEntryR\x06labels\x12'\n" +
	"\x0fservice_account\x18\x03 \x01(\tR\x0eserviceAccount\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ProvisionResponse2b\n" +
	"\x12ProvisionerService\x12L\n" +
	"\tProvision\x12\x1d.katartismos.ProvisionRequest\x1a\x1e.katartismos.ProvisionResponse(\x01B#Z!github.com/katastroma/katartismosb\x06proto3"

var (
	file_katartismos_provisioner_proto_rawDescOnce sync.Once
	file_katartismos_provisioner_proto_rawDescData []byte
)

func file_katartismos_provisioner_proto_rawDescGZIP() []byte {
	file_katartismos_provisioner_proto_rawDescOnce.Do(func() {
		file_katartismos_provisioner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_katartismos_provisioner_proto_rawDesc), len(file_katartismos_provisioner_proto_rawDesc)))
	})
	return file_katartismos_provisioner_proto_rawDescData
}

var file_katartismos_provisioner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_katartismos_provisioner_proto_goTypes = []any{
	(*ProvisionRequest)(nil),  // 0: katartismos.ProvisionRequest
	(*ProvisionResponse)(nil), // 1: katartismos.ProvisionResponse
	nil,                       // 2: katartismos.ProvisionRequest.LabelsEntry
}
var file_katartismos_provisioner_proto_depIdxs = []int32{
	2, // 0: katartismos.ProvisionRequest.labels:type_name -> katartismos.ProvisionRequest.LabelsEntry
	0, // 1: katartismos.ProvisionerService.Provision:input_type -> katartismos.ProvisionRequest
	1, // 2: katartismos.ProvisionerService.Provision:output_type -> katartismos.ProvisionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_katartismos_provisioner_proto_init() }
func file_katartismos_provisioner_proto_init() {
	if File_katartismos_provisioner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_katartismos_provisioner_proto_rawDesc), len(file_katartismos_provisioner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_katartismos_provisioner_proto_goTypes,
		DependencyIndexes: file_katartismos_provisioner_proto_depIdxs,
		MessageInfos:      file_katartismos_provisioner_proto_msgTypes,
	}.Build()
	File_katartismos_provisioner_proto = out.File
	file_katartismos_provisioner_proto_goTypes = nil
	file_katartismos_provisioner_proto_depIdxs = nil
}
