syntax = "proto3";

package katartismos;

option go_package = "github.com/katastroma/katartismos";

// ProvisionerService applies Kubernetes manifests to a cluster.
service ProvisionerService {
  rpc ProvisionStream(stream ProvisionStreamRequest) returns (stream ProvisionStreamResponse);
  rpc Provision(stream ProvisionRequest) returns (ProvisionResponse);
}

// Streamed Kubernetes manifest.
message ProvisionStreamRequest {
  bytes manifest = 1;
}

// Provisioned Kubernetes manifest.
message ProvisionStreamResponse {
  bytes manifest = 1;
}

// Streamed Kubernetes manifest.
message ProvisionRequest {
  bytes manifest = 1;
}

// Provisioned Kubernetes manifest.
message ProvisionResponse {}
